url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jie Gao (高洁)" # the name of your site, e.g. ACME Corp.
description:
